### ISSUE TITLE
Passing gradient option to simpleheat?

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet.heat#1]
Doesn't seem like this is possible via the current API

**Comment by morganherlocker** [comment]
Ideally this would be an array of color breaks, which would make it easier to keep colors from getting muddy in the middle. For example: (although it would probably need to take hexcodes or rgb vals instead of keys like this)

['red', 'yellow', 'green']

**Comment by tmcw** [comment]
The simpleheat api looks legit: https://github.com/mourner/simpleheat#appearance - it's just not accessible from this interface.

**Comment by mourner** [comment]
Gradient option here: https://github.com/Leaflet/Leaflet.heat#lheatlayerlatlngs-options
