### ISSUE TITLE
Zooming to bounds of points added.

### ISSUE THREAD

**Issue by paulmortlock** [Leaflet/Leaflet.heat#112]
I am getting an error when trying to zoom to the extents of the data I add.

var heat = L.heatLayer(data.features,cfg).addTo(map);
// Fit the map viewport to the bounds of the layers
map.fitBounds(heat.getBounds());

**Comment by IvanSanchez** [comment]
Instances of `L.HeatLayer` don't have a `getBounds()` method. Please read the documentation carefully to find out available methods.

Behaviour as expected, not a bug.
