### ISSUE TITLE
Heatmap from GeoJSON

### ISSUE THREAD

**Issue by rcrivera** [Leaflet/Leaflet.heat#12]
Is there any way that I can create a heatmap directly from a GeoJSON?

**Comment by tayden** [comment]
I'm also interested in this

**Comment by sergei-maertens** [comment]
Yeah, me too

**Comment by ryankdalton** [comment]
This would be a great enhancement!

**Comment by brianrusso** [comment]
+1

**Comment by xuejinruan** [comment]
I am also looking for the support of GeoJson data for heatmap. If we could optionally choose any attribute field as weighting factor, that would be ever better! Thanks!!!

**Comment by mattesCZ** [comment]
I think this plugin should have as simple API as possible. You can always transform your GeoJSON data with simple function like this:

```
function geoJson2heat(geojson, intensity) {
  return geojson.features.map(function(feature) {
    return [
      feature.geometry.coordinates[0][1],
      feature.geometry.coordinates[0][0],
      feature.properties[intensity]
    ];
  });
}
```

**Comment by princeshahnawaz2012** [comment]
While using this function to fetch the data...I get this following error....
Uncaught RangeError: Maximum call stack size exceeded on leaflet.js:6

var geoData = geoJson2heat(layer.data, 2); 
// returns  0: Array[3] 0: "42.3439925" 1: "-3.696906" 2: "4", 1: Array[3] 0: "38.2733071"1: "-3.6065861"2: "3" ..... 
var heatMap = L.heatLayer(geoData,{ radius: 20,blur: 15, maxZoom: 17})  
map.addLayer(heatMap);

function geoJson2heat(geojson, intensity) {
      return geojson.features.map(function(feature) {
        return [
          feature.geometry.coordinates[1],
          feature.geometry.coordinates[0],
          feature.properties[intensity]
        ];
      });
    }

**Comment by princeshahnawaz2012** [comment]
the main problem was double quotes in each array. Therefore, i did a tiny change(using parseFloat) in the same function and passing to directly L.heatLayer.. It seems working. 

var geoData = geoJson2heat(layer.data, intensity);
var heatMap = new L.heatLayer(geoData,{radius: 30,blur: 15, maxZoom: 17});

geoJson2heat = function(geojson, intensity) {
      return geojson.features.map(function(feature) {
        return [parseFloat(feature.geometry.coordinates[1]), parseFloat(feature.geometry.coordinates[0]), intensity];
      });
    }

**Comment by mourner** [comment]
I agree with @mattesCZ, it should be easy enough to transform GeoJSON into a flat list of coordinates.

**Comment by tomchadwin** [comment]
In the functions above to transform GeoJSON, what is `layer.data` in the first line? Is `layer` an `L.geoJSON`? If so, I don't see a `data` property.

In other words, what type is `layer` in the first line?

**Comment by abhishek-kumar-engineer** [comment]
thankyou @ajgeers and @Jmuccigr i solved this issue
geoJson2heat = function(geojson) {
return geojson.features.map(function(feature) {
return [parseFloat(feature.geometry.coordinates[1]), parseFloat(feature.geometry.coordinates[0])];
});
}

function addObsToMap(obs, map) {
var geoData = geoJson2heat(obs, 1);
var heatMap = new L.heatLayer(geoData,{radius: 50, blur: 25, maxZoom: 17});
map.addLayer(heatMap);
}
