### ISSUE TITLE
How to make the heat map layer below other layers?

### ISSUE THREAD

**Issue by feixia586** [Leaflet/Leaflet.heat#13]
I try to put this heat map layer under some geojson layers, but failed. Is there any suggestion to do that?

Thank you.

**Comment by danzel** [comment]
If you add the heat layer to the map first that should do it?

**Comment by feixia586** [comment]
That won't work... After I added the heat map layer, I removed the geojson layer and re-added it. I found the heat map was still on the top.

**Comment by mourner** [comment]
This is supported with Leafle 1.0 beta if you create a separate pane and pass it as the `pane` option. Not an issue of Leaflet.heat.
