### ISSUE TITLE
How to make heatmap look correct when no point intensity is supplied?

### ISSUE THREAD

**Issue by riostevenson** [Leaflet/Leaflet.heat#14]
For example This is what it looks like if i have array points added to map without point intensity
![error](https://cloud.githubusercontent.com/assets/5872814/3725727/b17a227a-168b-11e4-9cc4-b59013d362fd.png)  

As you can see this heat map doesnt really look like a heatmap.  I also used default options for heatmap so I have no idea.

**Comment by taylorkline** [comment]
Second this issue.

**Comment by mourner** [comment]
You can now specify `minOpacity` in options to handle things like this.
