### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by vitorleal** [Leaflet/Leaflet.heat#16]
There's any way to install it using [Bower](http://bower.io/)

**Comment by danbjoseph** [comment]
thanks for this great plugin, +1 for registering it on bower

**Comment by aurelian** [comment]
:+1:

**Comment by kikito** [comment]
:+1:

**Comment by Volox** [comment]
+1

**Comment by NejcZupec** [comment]
:+1:

**Comment by mourner** [comment]
I don't want to support Bower anymore. It's a huge pain to support for library authors, has serious design flaws and should go away. Please use NPM, Webpack or JSPM instead. Also see discussion here: https://github.com/bower/bower/issues/1520
