### ISSUE TITLE
Support for leaflet 0.8-dev

### ISSUE THREAD

**Issue by zheffie** [Leaflet/Leaflet.heat#17]
Any change for support for leaflet 0.8-dev?

Chrome throws following errror

Uncaught TypeError: Cannot read property 'call' of undefined leaflet.js:5
o.Map.o.Evented.extend.whenReady leaflet.js:5
o.Map.include.addLayer

**Comment by ilvalle** [comment]
+1

**Comment by RobbieTheWagner** [comment]
:+1:

**Comment by mourner** [comment]
I'll look into this, should be a matter of changing couple lines of code.

**Comment by RobbieTheWagner** [comment]
Thank you! :)

**Comment by RobbieTheWagner** [comment]
@mourner did you get a chance to look at this? If it is only a couple lines that need to be changed to support the new Layers extension, and you could tell me what those lines should look like, I could also start looking at some of the other layer plugins we are using and submit pull requests for the fix in other plugins to help this process along.

**Comment by mourner** [comment]
Done. As you can see, this was super-easy. Most plugins will only require one change — inheriting from `L.Layer` rather than `L.Class`.

**Comment by RobbieTheWagner** [comment]
Awesome, thanks! I appreciate your help.

**Comment by RobbieTheWagner** [comment]
I am in the process of updating all the plugins we use to support the new version of leaflet, and it appears that changing L.Class to L.Layer is not the only issue with Leaflet.heat. There is the following line in _animateZoom:

``` js
this._canvas.style[L.DomUtil.TRANSFORM] = L.DomUtil.getTranslateString(offset) + ' scale(' + scale + ')';
```

That method has been removed. What is the fix for this?

**Comment by mourner** [comment]
Did you actually look into the commit above?

**Comment by RobbieTheWagner** [comment]
Yeah, I looked at it. Is setTransform the new way of doing things? I just expected getTranslateString to no longer be used.

**Comment by mourner** [comment]
@rwwagner90 the commit above makes latest Leaflet.heat code work both with Leaflet 0.7.3 and Leaflet 0.8-dev.
