### ISSUE TITLE
problem overlaying two heatmaps

### ISSUE THREAD

**Issue by bolollo** [Leaflet/Leaflet.heat#2]
Hi Vladimir,

I just noticed a small glitch with the heatmaps library for Leaflet: there’s no way to overlay two heatmaps one on top of the other. 
Is it any simple to fix?

**Comment by ubuntufreak** [comment]
@bolollo Did you find any solution to overlay two heatmap layers using the plugin ? Even i'm trying to implement a similar feature.

@mourner Is it possible to create two objects of the L.heatLayer and embed both on the same map ?

**Comment by bolollo** [comment]
@ubuntufreak I have not found any solution. Currently I use a radio button in the Layers Control

**Comment by ubuntufreak** [comment]
@bolollo you mean like redrawing the heatmap's with different values based on the radio button ?

**Comment by mourner** [comment]
Did you try just adding two `L.heatLayer` objects to the same map?

**Comment by ubuntufreak** [comment]
@mourner yes i did try that like this https://gist.github.com/ubuntufreak/9950789
But only the first object is displayed in the map.

**Comment by mourner** [comment]
Sounds like a bug, I'll take a look.

**Comment by ubuntufreak** [comment]
@mourner thanks for taking time to look into this !

**Comment by marks** [comment]
@mourner - any update? very interesting in doing this as well.

**Comment by mourner** [comment]
Should be fixed now.

**Comment by marks** [comment]
@mourner - thanks!!

**Comment by ubuntufreak** [comment]
@mourner thanks works fine now !
