### ISSUE TITLE
Setting opacity and Z index for Heat layer

### ISSUE THREAD

**Issue by dcurletti** [Leaflet/Leaflet.heat#24]
How would you go about toggling a heat layer's opacity on/off and adjusting the Z index- in reference to having multiple heat layers on the same map?  Mainly just worried about the opacity, but the z index would be nice. 

Thanks!

**Comment by gofizz** [comment]
Hey, look in to creating custom panes in leaflet 0.8 (dev). You will need to modify the code in Heatlayer class to be able to use your custom pane. You can store your custom pane and modify its css and set its opacity or z-index.

**Comment by dcurletti** [comment]
Ok cool I will look into it.  Appreciate the help.

**Comment by benderlidze** [comment]
Got any example with custom pane and heat layer? Thanks
