### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by 11samype** [Leaflet/Leaflet.heat#26]
I am trying to implement a heatmap with high opacity but when I set minOpacity it seems to not have any effect. Is there something I am missing?

**Comment by mourner** [comment]
Can you set up a JSFiddle reproducing your problem?

**Comment by 11samype** [comment]
http://jsfiddle.net/wSytj/79/

minOpacity at line 48

**Comment by mourner** [comment]
Just confirmed minOpacity works properly in the latest release, the one in JSFiddle was probably an outdated build.
