### ISSUE TITLE
Built-in support for IDW heatmaps?

### ISSUE THREAD

**Issue by fullofcaffeine** [Leaflet/Leaflet.heat#30]
Hi!

Thanks for this library!

I'm trying to create a heatmap like the one below:

<img width="672" alt="screenshot 2015-07-10 17 17 09" src="https://cloud.githubusercontent.com/assets/81248/8630211/98a9995c-2728-11e5-9d94-3470b5a8c64f.png">

(Source: https://www.walkscore.com/choice/restaurants/NY/New_York)

It uses IDW - https://en.wikipedia.org/wiki/Inverse_distance_weighting. Notice also that the heatmap layer doesn't change as you zoom in/out.

I'm wondering if Leaflet.heat supports this kind of heatmap visualization? Or is it something I'd have to implement manually?

Thanks!

**Comment by mourner** [comment]
No support for this kind of visualization currently. Also see https://github.com/mourner/simpleheat/issues/3

**Comment by fullofcaffeine** [comment]
Hi Vladimir,

Thank your for the reply. 

Excerpt from mourner/simpleheat#3:

> For this to work as heatmaps, we would need to combine point clustering with interpolation, which is not >as simple, and getting sane results from this might involve a lot of tweaking.

Do you know any other (open-source) javascript solution that implements that? Do you plan to support this in a near future for the `Leaflet.heat` plugin?

When you say it might involve a lot of tweaking, what do you mean exactly?

It's strange that these methods are not readily available currently in open-source mapping javascript libraries, since it looks like a very popular visualization. What do you think?

Thank you very much for your time and help!
