### ISSUE TITLE
Incompatible plugin with Leaflet 1.0.dev

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet.heat#34]
Could you please update project to be compatible with latest Leaflet 1.0.dev?
It has essential bug fixes, but with that one Leaflet.heat doesn't work at all.

All what do I have is this error "Uncaught TypeError: Cannot read property 'lat' of null"

**Comment by snkashis** [comment]
You may want to provide a jsfiddle of your example case, because with Leaflet 1.0 b1 things are operating fine.

**Comment by mourner** [comment]
Made sure the latest version works with beta2 (including fixed animations). Will make a new release today.
