### ISSUE TITLE
Intensity does not work, NO documentation

### ISSUE THREAD

**Issue by boysmovie** [Leaflet/Leaflet.heat#36]
Intensity does not work and there is NO real documentation for this plugin.

multiple developers have this problem. Please fix.

http://stackoverflow.com/questions/26767722/leaflet-heat-issue-with-adding-points-with-intensity

**Comment by mourner** [comment]
Clarified the documentatio, hopefully it'll be enough. Made sure intensity works as expected, maybe be you were using an outdated build?
