### ISSUE TITLE
IE9 -heatmap position is off after panning

### ISSUE THREAD

**Issue by matejmuza** [Leaflet/Leaflet.heat#4]
Not sure if Leaflet.heat supports IE9... There seems to be an issue with heatmap layer positioning after user pans around the map.

![ie9_heat_1](https://f.cloud.github.com/assets/4689746/2393201/d3f68442-a98a-11e3-92d1-a8c0c5c1c16e.PNG)

![ie9_heat_2](https://f.cloud.github.com/assets/4689746/2393202/d805daf6-a98a-11e3-81d2-2ad63c36913f.PNG)

If anybody else needs to support IE9, adding 'position:absolute;' to '.leaflet-heatmap-layer' seems to do the trick.

**Comment by zedd45** [comment]
Thanks @matejmuza, that fix worked for me in IE9 as well.

@mourner I'll submit a pull request later today.  I'm thinking just apply style.position = "absolute" and a top / left value.

**Comment by mourner** [comment]
Oops, thanks for figuring this out guys :)

**Comment by zedd45** [comment]
Thank for continuing to make awesome stuff.  Nice trick on the npm install post hook to build the bundle, too.  Hadn't seen that one before.

**Comment by mourner** [comment]
Should be fixed with https://github.com/Leaflet/Leaflet.heat/commit/9a41e607d2c22d07543e9e979b3d599d686d2129 now
