### ISSUE TITLE
add support bower

### ISSUE THREAD

**Issue by coolblades** [Leaflet/Leaflet.heat#41]
Hi,
I would like to use your library for our development (replace the old git://github.com/johnthillaye/Leaflet.heat.git). We are using bower to pull the libraries, and is it possible to add bower support to your library?

Thanks

Jonathan

**Comment by yohanboniface** [comment]
See https://github.com/Leaflet/Leaflet.heat/issues/16#issuecomment-155834094

**Comment by coolblades** [comment]
sorry about that.
