### ISSUE TITLE
Intensity doesn't work correctly

### ISSUE THREAD

**Issue by danielopitz** [Leaflet/Leaflet.heat#5]
When intesity is provided as altitude it isn't computed properly (the values are too small and everything is trated as value 1). To get it to work correctly I changed two bits of code in the _redraw function:
- line 144

```
k = this._latlngs[i].alt || (1 * v);
```

Multiplying the alt with v makes it really small, so I went for not doing it.
- line 168

```
Math.max(cell[2], 1)
```

If the values are too small in line 144 this will always be < 1 and after changing line 144 it will always be 1 if Math.min() is still used.
As far as I can see it produces a result which looks better, but still isn't really correct IMO. I used this data for testing:

```
{max: 70, data: [{lat: 0, lon: 0, value: 0},{lat: 10, lon: 10, value: 10},{lat: 20, lon: 20, value: 20},{lat: 30, lon: 30, value: 30},{lat: 40, lon: 40, value: 40},{lat: 50, lon: 50, value: 50},{lat: 60, lon: 60, value: 60},{lat: 70, lon: 70, value: 70}]}
```

and when zoomed out max it doesn't look correctly to me.

**Comment by Guitlle** [comment]
Hi @danielfox , my pull requests (issue #8 ) shows a relative heat map based on the minimums and maximums of the visible points instead of the zoom. I tested it with random data and looks good for few points
![urban data3](https://cloud.githubusercontent.com/assets/2118234/2722292/54e09086-c586-11e3-97cf-7eadee25aedc.png)

**Comment by ryansit** [comment]
+1, a relative heatmap would be a huge improvement

**Comment by RobbieTheWagner** [comment]
I noticed after updating to the new version, our heat didn't look very good. It's related to this issue. Why was https://github.com/Leaflet/Leaflet.heat/blob/gh-pages/src/HeatLayer.js/#L145 changed? It used to be: 

``` js
alt = this._latlngs[i].alt || this._latlngs[i][2];
      k = alt || (1 * v);
```

Why is `this._latlngs[i][2]` no longer supported?

@mourner, if there is not a pressing reason for it to have been changed, would you accept a PR to put it back? If there was a reason, we'll need to restructure all of our data. Please let me know.

**Comment by mourner** [comment]
> Why is this._latlngs[i][2] no longer supported?

It's accidental probably. There's a pull for this already: https://github.com/Leaflet/Leaflet.heat/pull/20
Will merge soon.

**Comment by RobbieTheWagner** [comment]
Okay, awesome. Thanks!

**Comment by fredericbonifas** [comment]
Hi,

At his line, I don't understand why we take the minimum between the cell's value and 1:
https://github.com/Leaflet/Leaflet.heat/blob/gh-pages/src/HeatLayer.js/#L172

Shouldn't it be

```
Math.min(cell[2], this.options.max)
```

instead of 

```
Math.min(cell[2], 1)
```

?

**Comment by torfsen** [comment]
@fredericbonifas: I think so, too. The change works for me, so here's a [minimal pull request](https://github.com/Leaflet/Leaflet.heat/pull/28).

**Comment by torfsen** [comment]
@mourner: That was quick :+1:
