### ISSUE TITLE
I just can test your examples on Safari

### ISSUE THREAD

**Issue by jmpatricior** [Leaflet/Leaflet.heat#50]
I'm testing your examples but i can only get them to work on Safari, have you hear of any incompatibilities with other browsers?
It works here ( http://leaflet.github.io/Leaflet.heat/demo/draw.html ) without any flaws, but when i try to copy your code, and run in my app it only works with Safari, doesn't show any error, i can't see any heatmap points, just the map.

Any help would be appreciated.

Best regards,
João Rodrigues

**Comment by mourner** [comment]
It's probably a http/https mismatch, and is not related to the code. Also, this is not a support forum — please use StackOverflow for questions like this. GitHub issues are for project issues.
