### ISSUE TITLE
Heatmap tile not updating on drag

### ISSUE THREAD

**Issue by simonvandel** [Leaflet/Leaflet.heat#51]
In [example](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-heat-markers/) the heatmap is only loaded after a drag has ended, resulting in a half drawn heatmap.
See [this picture](http://imgur.com/StMdUNG) for a visual explanation.

What can be done to draw heatmaps while dragging or alternatively always have the heatmap drawn even if not inside the current viewport?

**Comment by mourner** [comment]
This is working as intended for performance reasons.

**Comment by simonvandel** [comment]
@mourner Is there a way to do it anyway if performance is not a factor?

**Comment by mourner** [comment]
It's possible by changing the source code. Pull requests welcome.

**Comment by LeddoEngano** [comment]
Hey, I have created a version that has the smooth drag + Level of detail to help with the performance issues! Hope it helps :)

https://github.com/felipexy/leaflet_heat_smooth
