### ISSUE TITLE
question regarding performance

### ISSUE THREAD

**Issue by geraldstanje** [Leaflet/Leaflet.heat#54]
Hi,

great demo.

is the heatmap able to handle 200k data points (lat/long)? i plan to add the points on the fly, e.g. addLatLng, so will it slow down the rendering?

you set the default radius to 25, what does it mean? does the radius scale based on map zoom?

Thanks

**Comment by mourner** [comment]
GitHub issues is a place to report bugs, not to ask support questions. Please use StackOverflow, or simply try feeding 200k points into Leaflet.heat and see how that works.

**Comment by geraldstanje** [comment]
github also has the feature to ask questions... reference: https://github.com/Leaflet/Leaflet/issues/4403

**Comment by IvanSanchez** [comment]
I feel obliged to link to [How To Ask Questions The Smart Way](http://catb.org/~esr/faqs/smart-questions.html).

We are likely to answer questions (and feature requests) which show a good amount of independent previous research, and which might improve Leaflet's features or performance. But questions about how to use Leaflet for your specific use case? Nope. That's what [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) and [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet) are for.
