### ISSUE TITLE
What license do you use?

### ISSUE THREAD

**Issue by kennynaoh** [Leaflet/Leaflet.heat#57]
Hello @mourner ,
I am the member of the [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
What license do you use?
References this [website](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json).
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by IvanSanchez** [comment]
https://github.com/Leaflet/Leaflet.heat/blob/gh-pages/LICENSE
