### ISSUE TITLE
max option not working

### ISSUE THREAD

**Issue by cpunekar** [Leaflet/Leaflet.heat#63]
When I set the max value to 5, I am getting following error in my browser:

_Uncaught IndexSizeError: Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (5) is outside the range (0.0, 1.0)_

**Comment by songyanho** [comment]
Please provide your initialisation code so that we can help?

**Comment by cpunekar** [comment]
var myVar = L.heatLayer(dataPoints, {
            max: 5.0,
            radius: 12,
            blur: 25,
            maxZoom: 11,
            gradient: {
              0.4: 'blue', 1: 'lime', 5.0: 'red'
            }
       });

**Comment by luispina** [comment]
I'm so sorry to write in a closed thread, but i'm having the same problem. Was there any solution, @cpunekar ?

Thanks in advice for any help.

**Comment by maurerle** [comment]
Had the same issue - tried to set the layer first with max value and then update the options using 
`myVar.setOptions({gradient: {0.4: 'blue', 1: 'lime', 5.0: 'red'}})`

which did also not work.

I therefore scaled all the values by dividing through the maxvalue and using this as intensity
