### ISSUE TITLE
error loading my own points

### ISSUE THREAD

**Issue by vlasvlasvlas** [Leaflet/Leaflet.heat#7]
trying the 10.000 points example, 

i got this error
"Uncaught TypeError: Cannot read property '0' of undefined "

sample of my data:

---

var addressPoints = [
[-35.4185239604101, -60.1819977605355,"540"],
[-35.4256691043552, -60.1671376727503,"711"] 
.....
];

**Comment by danzel** [comment]
We're going to need more info than this.
Please create a minimal jsfiddle.
