### ISSUE TITLE
Disabled layers control on MaxZoom

### ISSUE THREAD

**Issue by Crashillo** [Leaflet/Leaflet.heat#79]
I've noticed when you zoom in, exceeding the maxZoom property (set by L.heatLayer options), the layer control checkbox is disabled. Why so?

I've two heatMaps, and mainly I need to depict the data at lower zoom, in a world-wide view, and to choose between maps; but if I zoom in over than maxZoom, selection is gone. Is it a bug, or has it any reason?

![chkbox-disabled](https://cloud.githubusercontent.com/assets/817526/21543565/eb01615c-cdc7-11e6-8024-f631e11e0f0e.png)

**Comment by rrooij** [comment]
Same problem here. It would be nice to see this fixed.

**Comment by IvanSanchez** [comment]
It's a Leaflet feature, not a bug. See https://github.com/Leaflet/Leaflet/pull/3694

If you have two different Leaflet layers, one for low zooms and one for high zooms, and want to enable/disable them both at the same time, create a `L.LayerGroup` with them, add add the group to the layers control instead.
