### ISSUE TITLE
How to redraw the map

### ISSUE THREAD

**Issue by devux** [Leaflet/Leaflet.heat#85]
Hi friends,
         I've done the heat map using this code
var heat = L.heatLayer(addressPoints, {radius: 25},{gradient: {1: 'blue', 0.65: 'lime', 1: 'red'}}).addTo(map);
but now I've have to redraw the map with new set of data, How to do it? 
Any syntax or code snippets is there please share here.

I've tried to use redraw() method but its not working for me so how to use it ?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
