### ISSUE TITLE
does leaflet.heat support Vue.js2?

### ISSUE THREAD

**Issue by zhuyinjing** [Leaflet/Leaflet.heat#88]
hi,
i use `import "leaflet.heat"` in my project ,
and i use ` 
var arrheatmap=[[0,0,1]];
var heat = L.heatLayer(arrheatmap, {
        radius: 20
       }).addTo(this.map);
`
it doesn't work,and it doesn't show error. what's wrong ?

**Comment by zhuyinjing** [comment]
i use Vue.js in my project.

**Comment by angel-langdon** [comment]
hey, did you solve it? i want to use this library in react, how can i?
Note: I don't want to use the react-leaflet-heatmap library, i want to use Leaflet.heat
